# Generated by Django 5.0.3 on 2024-03-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_remove_group_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
    ]
