# Generated by Django 5.0.3 on 2024-04-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_writer_remove_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mindfulnesstask',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.DeleteModel(
            name='ExerciseTask',
        ),
        migrations.DeleteModel(
            name='MindfulnessTask',
        ),
    ]
