# Generated by Django 5.0.3 on 2024-04-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_remove_chatgroup_created_at_remove_chatgroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chatgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
