# Generated by Django 5.0.3 on 2024-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_remove_task_bonus_task_description_task_max_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_bonus',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='progress_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
