# Generated by Django 5.0.3 on 2024-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0107_alter_therapist_therapist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='therapist_id',
        ),
        migrations.AddField(
            model_name='therapist',
            name='id',
            field=models.IntegerField(primary_key=True),
        ),
    ]
