# Generated by Django 5.0.3 on 2024-04-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0108_remove_therapist_therapist_id_therapist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
