# Generated by Django 5.0.3 on 2024-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_profile_role_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('therapist', 'Therapist'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
