# Generated by Django 5.0.3 on 2024-03-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_therapist_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
    ]
