# Generated by Django 5.0.3 on 2024-03-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='therapists/')),
                ('role', models.CharField(choices=[('therapist', 'Therapist'), ('member', 'Member')], default='therapist', max_length=200)),
            ],
        ),
    ]
