# Generated by Django 5.0.3 on 2024-03-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_group_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
