# Generated by Django 5.0.3 on 2024-03-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_group_volunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
