# Generated by Django 5.0.3 on 2024-03-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_group_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteered_at',
        ),
    ]
