# Generated by Django 5.0.3 on 2024-04-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_alter_task_max_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='bonus_earned',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
