# Generated by Django 5.0.3 on 2024-04-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0102_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
