# Generated by Django 5.0.3 on 2024-04-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0110_alter_therapist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='id',
            new_name='therapist_id',
        ),
    ]
